spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joyoji/springapps-petclinic-microservices-config
        native:
          search-locations: classpath:.
  profiles:
    active: native
